# Generated by Django 3.1 on 2020-10-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
