# Generated by Django 3.1 on 2020-10-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20201016_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
                ('portfolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.portfolio')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=30)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('portfolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.portfolio')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
