# Generated by Django 3.1 on 2020-10-16 20:57

import broker.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_card_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(default='noimage.png', upload_to=broker.models.profile.id_back_store),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(default='noimage.png', upload_to=broker.models.profile.id_front_store),
        ),
    ]
