# Generated by Django 3.1 on 2020-10-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_auto_20201018_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ssn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
