# Generated by Django 3.1 on 2020-10-24 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_auto_20201024_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
