# Generated by Django 3.1 on 2020-10-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_auto_20201024_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='date_created',
        ),
    ]
