# Generated by Django 3.1 on 2020-10-24 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_auto_20201024_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
