# Generated by Django 3.1 on 2020-10-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
    ]
